### ISSUE TITLE
Uptime Kuma support existing claim

### ISSUE THREAD

**Issue by hans99** [duyet/charts#53]
Would it be possible to have pvc support for existing claim, like:

  {{- if .Values.persistence.existingClaim }}
  existingClaim: {{ .Values.persistence.existingClaim }}
  {{- end }}

**Comment by duyet** [comment]
@hans99 Thank you for reaching out. I've updated the helm chart to support `existingClaim` for persistence volume. Please check out the https://github.com/duyet/charts/pull/54

```yaml
persistence:
   enabled: true
   existingClaim: my-pvc
```
